package lesson04.part03;
//@FoLoKe
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

import static org.junit.Assert.*;

@RunWith(JUnit4.class)
public class Task48Test {
    /* 1.	В классе Solution должно быть 4 вложенных класса: MyException, MyException2, MyException3 и MyException4.
     * 2.	Все вложенные классы должны быть унаследованы от классов исключений.
     * 3.	Два класса из четырех должны быть checked исключениями.
     * 4.	Два класса из четырех должны быть unchecked исключениями.
     *
     */

    @Test
    public void test48main() {

    }

    @Test
    public void test4801() {

    }

    @Test
    public void test4802() {

    }

    @Test
    public void test4803() {

    }

    @Test
    public void test4804() {

    }
}